print 'NVIM Config Loaded!'

require 'pjpirie.options'
require 'pjpirie.keymaps'
require 'pjpirie.plugins'
require 'pjpirie.cmp'
require 'pjpirie.lsp'
require 'pjpirie.telescope'
require 'pjpirie.treesitter'
require 'pjpirie.autopairs'
require 'pjpirie.comment'
require 'pjpirie.gitsigns'
require 'pjpirie.nvimtree'
require 'pjpirie.bufferline'
require 'pjpirie.toggleterm'
require 'pjpirie.lsp.null-ls'
require 'pjpirie.db'
require 'pjpirie.navigator'
require 'pjpirie.lualine'
require 'pjpirie.jester'
require 'pjpirie.packagejson'
require 'pjpirie.hop'
require 'pjpirie.lightbulb'

